global:
  resolve_timeout: 5m

route:
  receiver: default-webhook
  group_by: [alertname, severity]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2h
  routes:
    - matchers:
        - severity = critical
      receiver: pager
      group_wait: 5s
      continue: false
    - matchers:
        - team = shop
      receiver: shop-webhook
      group_by: [alertname, env]

inhibit_rules:
  - source_matchers:
      - alertname = InstanceDown
    target_matchers:
      - alertname = HighErrorRate
    equal: [instance]

receivers:
  - name: default-webhook
    webhook_configs:
      - url: http://sample-app:8000/webhook
        send_resolved: true
  - name: pager
    webhook_configs:
      - url: http://sample-app:8000/webhook
        send_resolved: true
  - name: shop-webhook
    webhook_configs:
      - url: http://sample-app:8000/webhook
        send_resolved: true
