groups:
  - name: pca.recording
    interval: 15s
    rules:
      - record: job:http_requests:rate5m
        expr: sum by (job, code) (rate(http_requests_total[5m]))

      - record: job:http_request_error_ratio:rate5m
        expr: |
          sum by (job) (rate(http_requests_total{code=~"5.."}[5m]))
          /
          sum by (job) (rate(http_requests_total[5m]))

      - record: instance:node_cpu:rate5m
        expr: |
          sum by (instance) (
            rate(node_cpu_seconds_total{mode!="idle"}[5m])
          )
