FROM docker.io/library/python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 8000
ENV PORT=8000 APP_VERSION=1.4.2 PYTHONUNBUFFERED=1

CMD ["python", "app.py"]
